name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
  token:
    description: "Github repository token"
  target_url:
    description: "Target url location"
  description:
    description: "Descriptive message about the deployment"
  auto_merge:
    description: Whether to attempt to auto-merge the default branch into the branch that the action is running on if set to `"true"`
    default: false
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
  transient_environment:
    description: "Specifies if the environment is specific to the deployment and will no longer exist in future"
    default: false
  environment_url:
    description: "URL for accessing the environment"
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "lib/main.js"
